name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          set -ex
          npm ci lix --ignore-scripts
          npx lix download

      - name: Build
        run: |
          npx haxe build.hxml

  examples:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ['js', 'neko', 'interp', 'hl']
        haxe-version: [3.4.7, 4.2.5, latest]
        exclude:
          - haxe-version: 3.4.7
            target: 'interp'

    steps:
      - uses: actions/checkout@v3

      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ matrix.haxe-version }}

      - name: Install Dependencies
        run: |
          haxelib install utest

      - name: Install hx4compat
        run: |
          if: (matrix.target == 'latest')
          haxelib git hx4compat https://github.com/HaxeFoundation/hx4compat.git

      - name: Build
        run: |
          cd tests
          haxe RunCi.hxml
          neko RunCi.n ${{ matrix.target }}
